### ISSUE TITLE
panic error while simply running "tftag" on the terraform repo

### ISSUE THREAD

**Issue by 99** [bschaatsbergen/tftag#8]
Followed readme steps created .tftag.hcl 
```tftag "all" {
  tags = {
    Taem = "Devops"
  }
}
```
and just executed tftag in the repo with tf code , this was the output
```
➜  terraform git:(main) ✗ tftag
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/bschaatsbergen/tftag/pkg/core.getResourceInfo(0x1400017e940)
	/home/runner/work/tftag/tftag/pkg/core/core.go:46 +0xb4
github.com/bschaatsbergen/tftag/pkg/core.processFile({0x10305f325, 0x1}, {{0x1400012e810?, 0x0?, 0x0?}}, {0x10316d6a8, 0x1400017e740})
	/home/runner/work/tftag/tftag/pkg/core/core.go:87 +0x224
github.com/bschaatsbergen/tftag/pkg/core.Main({0x10305f325, 0x1})
	/home/runner/work/tftag/tftag/pkg/core/core.go:36 +0x104
github.com/bschaatsbergen/tftag/cmd.glob..func1(0x103338020?, {0x103060011?, 0x0?, 0x0?})
	/home/runner/work/tftag/tftag/cmd/root.go:32 +0x34
github.com/spf13/cobra.(*Command).execute(0x103338020, {0x140001101d0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x103338020)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/bschaatsbergen/tftag/cmd.Execute()
	/home/runner/work/tftag/tftag/cmd/root.go:50 +0x28
main.main()
	/home/runner/work/tftag/tftag/main.go:6 +0x1c
```

**Comment by bschaatsbergen** [comment]
Hey Nat,

Could you try this:


```
tftag "all" {
  tags = {
    Foo = "Bar",
  }
}
```
